name: q_and_u_furniture
version: 1.0.5+6
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  external_path: ^1.0.3
  flutter_downloader: ^1.9.2
  flutter_file_downloader: ^1.1.2
  dio: ^5.2.0+1
  path_provider: ^2.0.14
  open_file_plus: ^3.4.1
  android_intent_plus: ^3.1.6
  permission_handler: ^8.1.5
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  responsive_sizer: ^3.1.1
  dots_indicator: ^2.1.0
  google_fonts:
  iconsax: ^0.0.8
  badges: ^3.0.2
  fluttertoast: ^8.1.2
  carousel_slider: ^4.1.1
  dotted_border: ^2.0.0+2
  share_plus: ^4.0.10
  speech_to_text: ^5.6.0
  sqflite: ^2.0.3
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^9.7.0
  image_picker: ^0.8.5+3
  overlay_support: ^2.0.1
  flutter_map: ^2.0.0
  geolocator: ^9.0.1
  qr_code_scanner: ^1.0.0
  lazy_load_scrollview: ^1.3.0
  infinite_scroll_pagination: ^3.2.0
  extended_nested_scroll_view:
  expandable: ^5.0.1
  esewa_flutter_sdk:
    path: ./esewa_flutter_sdk
  readmore: ^2.2.0
  firebase_dynamic_links: ^5.3.3
  webview_flutter: ^4.5.0
  font_awesome_flutter: ^10.1.0
  geocoding: ^2.0.4
  otp_text_field: ^1.1.3
  cached_network_image:
  internet_connection_checker: ^0.0.1+4
  flutter_secure_storage:
  get_storage: ^2.0.3
  device_preview: ^1.1.0
  hexcolor: ^2.0.7
  flutter_elegant_number_button: ^0.0.6
  loading_animation_widget: ^1.2.0+2
  url_launcher: ^6.1.10
  dropdown_button2: ^1.7.2
  khalti_flutter: ^2.2.0
  google_sign_in: 
  flutter_facebook_auth: ^5.0.11
  firebase_auth: ^4.2.5
  custom_refresh_indicator: ^2.0.0
  avatar_glow: ^2.0.2
  smart_auth: ^1.0.6
  pinput: ^2.2.16
  flutter_typeahead: ^4.6.1
  autocomplete_textfield:
  change_app_package_name: ^1.1.0
  connectivity_plus: ^3.0.2
  shimmer: ^2.0.0
  flutter_html: ^3.0.0-alpha.6
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html_core: ^0.10.0
  flutter_facebook_keyhash: ^0.0.4
  flutter_login_facebook: ^1.8.0
  google_maps_flutter: ^2.3.0
  marquee: ^2.2.3
  pie_chart: ^5.3.2
  intl: ^0.18.1
  photo_view: ^0.14.0
  # pdf: ^3.1.0
  # path_provider: ^2.0.11
  # open_file: ^3.2.0
  # # package_info_plus: ^3.0.2
  # ffi: ^1.0.3

# dependency_overrides:
#   firebase_core: ^1.19.1
#   firebase_messaging: ^11.4.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon.png"
